name: Clockwork

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Formatting:
    uses: ./.github/workflows/clang-format.yml
  Compilation:
    uses: ./.github/workflows/compilation.yml
  Linter:
    uses: ./.github/workflows/linter.yml
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
  Prerelease:
    needs: [Compilation]
    uses: ./.github/workflows/prerelease.yml
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
    permissions:
      contents: write
