name: Compilation

on:
  workflow_call:

jobs:
  compilation:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check compiler
        run: ${{ matrix.compiler }} -v

      - name: Build Debug
        run: make debug=yes CXX=${{ matrix.compiler }}

      - name: Clean build
        run: make clean

      - name: Build Release
        run: make CXX=${{ matrix.compiler }}
